<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
		<AssemblyVersion>5.0.25333.2</AssemblyVersion>
		<PackageVersion>$(AssemblyVersion)</PackageVersion>
		<RepositoryUrl>https://github.com/x600/alphacloud-messagepack</RepositoryUrl>
		<NuGetSourceRelease>https://nuget.pkg.github.com/x600/index.json</NuGetSourceRelease>
	</PropertyGroup>

	<Target Name="PostBuildRelease" AfterTargets="Pack" Condition="'$(NuGetSourceRelease)' != '' And '$(Configuration)' == 'Release'">
		<Exec Command="echo $(NuGetPath)nuget.exe push &quot;$(MSBuildProjectDirectory)\bin\$(Configuration)\$(MSBuildProjectName).$(PackageVersion).nupkg&quot; $(NugetPublishPassword) -Source &quot;$(NuGetSourceRelease)&quot; -Verbosity Detailed" />
	</Target>


	<PropertyGroup Label="Build">
		<TargetFrameworks>$(ApplicationTargetFrameworks)</TargetFrameworks>
	</PropertyGroup>

	<PropertyGroup Label="Package">
		<PackageTags>messagepack msgpack mvc-core formatter alphacloud</PackageTags>
		<Description>MessagePack formatters for ASP.NET Core MVC</Description>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\Alphacloud.MessagePack.HttpFormatter\Internal\SerializableTypesCache.cs" Link="SerializableTypesCache.cs" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Update="JetBrains.Annotations" Version="2025.2.4" />
		<PackageReference Update="MessagePack" Version="3.1.4" />
	</ItemGroup>

</Project>
